<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div>
    <?php if ($block->getStatus() == "tuna_Authorized" ) { ?>
        <h2><?php echo __('Compra concluída com sucesso # <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h2>
    <?php } else { ?>
        <h2><?php echo __('Sua compra esta sendo processada. Número do pedido # <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h2>
    <?php } ?>

    <div>
        <p>Você comprou</p>
        <table>
            <tr>
                <th>#</th>
                <th>Produto</th>
                <th>Preço</th>
                <th>Quantidade</th>
            </tr>
            <?php foreach ($block->getOrderProducts() as $key => $product) : ?>
                <tr>
                    <td><?php echo $key+1 ?></td>
                    <td><?php echo $product["ProductDescription"] ?></td>
                    <td><?php echo $product["Amount"] ?></td>
                    <td><?php echo $product["ItemQuantity"] ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>