<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div>
    <h2><?php echo __('Pedido de compra concluído com sucesso # <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h2>
    <h3><?php echo __('Clique <a href="%1" target="_blank"> aqui</a> e imprima seu boleto para realizar o pagamento', $block->escapeHtml($block->getBoletoURL())) ?></h2>

    <div>
        <p>Você comprou</p>
        <table>
            <tr>
                <th>#</th>
                <th>Produto</th>
                <th>Preço</th>
                <th>Quantidade</th>
            </tr>
            <?php foreach ($block->getOrderProducts() as $key => $product) : ?>
                <tr>
                    <td><?php echo $key + 1 ?></td>
                    <td><?php echo $product["ProductDescription"] ?></td>
                    <td><?php echo $product["Amount"] ?></td>
                    <td><?php echo $product["ItemQuantity"] ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>