<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div>
    <h2><?php echo __('Compra concluída com sucesso # <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h2>
    <div>
        <p>Você comprou</p>
        <table>
            <tr>
                <th>
                <th>Produto</th>
                <th>Preço</th>
                <th>Quantidade</th>
                <th>Preço</th>
                </th>
            </tr>
            <tr>
  
            </tr>
        </table>
    </div>
</div>