<?php
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div>
    <h2><?php echo __('Tivemos um problema ao processar esse pagamento #<span>%1</span>: <span>%2</span>', $block->escapeHtml($block->getOrderId()), $block->escapeHtml($block->getStatus())) ?></h2>
   <table>
    <?php foreach ($block->getOrderProducts() as $key => $product) : ?>
        <tr>         
            <td><?php echo $product["ProductDescription"] ?> - <a href="<?php echo $product["ProductUrl"] ?>"> Tente novamente</a> </td>         
        </tr>
    <?php endforeach; ?>
 </table>
</div>