<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div>
    <?php if ($block->getStatus() == "tuna_Captured" || $block->getStatus() == "tuna_PendingCapture") { ?>
        <h2><?php echo __('Compra concluída com sucesso # <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h2>
        <?php if ($block->getIsBoleto() == "true") { ?>
            <h2><?php echo __('Clique <a href="%1" target="_blank"> aqui</a> e imprima seu boleto para realizar o pagamento', $block->escapeHtml($block->getBoletoURL())) ?></h3>
            <?php } ?>
        <?php } else { ?>
            <h2><?php echo __('Sua compra esta sendo processada. Número do pedido # <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></h2>
        <?php } ?>

        <div>
            <p>Você comprou</p>
            <table>
                <tr>
                    <th>#</th>
                    <th>Produto</th>
					<th>Quantidade</th>
                    <th>Preço Final</th>
                   
                </tr>
                <?php foreach ($block->getOrderProducts() as $key => $product) : ?>
                    <tr>
                        <td><?php echo $key + 1 ?></td>
                        <td><?php echo $product["ProductDescription"] ?></td>                        
                        <td><?php echo $product["ItemQuantity"] ?></td>
						<td><?php echo number_format((float)$product["Amount"]*$product["ItemQuantity"], 2, ',', '') ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
</div>